### PR TITLE
dist-feed: Remove from sumo

### PR DESCRIPTION
**Pull request by chaitu236**
Remove dist-feed/* from sumo as we are going to use it from hardknott.

### Testing
None

### CODE REVIEW

**Review by amstewart — COMMENTED** [review]
I don't think the `dist-feed` definition file will continue to live in GH, in the long term. In the near-term, I think we can assert that the dist feed should build from the latest mainline ref (hardknott).

So I would be in favor of not bothering to cherry-pick this addition to `nilrt/master/sumo`. In fact, assuming that the ni-central and heisenberg build jobs area already pointing at hardknott, we should drop these `**/jenkins/dist-feed/*` files from the `nilrt/master/sumo` source entirely.

**Comment by chaitu236** [comment]
> I don't think the `dist-feed` definition file will continue to live in GH, in the long term. In the near-term, I think we can assert that the dist feed should build from the latest mainline ref (hardknott).
> 
> So I would be in favor of not bothering to cherry-pick this addition to `nilrt/master/sumo`. In fact, assuming that the ni-central and heisenberg build jobs area already pointing at hardknott, we should drop these `**/jenkins/dist-feed/*` files from the `nilrt/master/sumo` source entirely.

ni-central job currently pulls default branch (which is `nilrt/master/sumo`) and heisenberg job explicitly points to `nilrt/master/sumo`. Should I switch both to `nilrt/master/hardknott`?

**Comment by amstewart** [comment]
> ni-central job currently pulls default branch (which is `nilrt/master/sumo`) and heisenberg job explicitly points to `nilrt/master/sumo`. Should I switch both to `nilrt/master/hardknott`?

Yes; please do.

**Comment by amstewart** [comment]
Additionally, I'll go ahead and switch the default branch for the NILRT repos to `nilrt/master/hardknott`.

**Comment by chaitu236** [comment]
> Additionally, I'll go ahead and switch the default branch for the NILRT repos to `nilrt/master/hardknott`.

Ok, if you're switching default to `nilrt/master/hardknott`, I'll won't touch azdo job as that pulls default. I've fixed heisenberg to point to `nilrt/master/hardknott`

**Review by billpittman — APPROVED** [review]

**Comment by chaitu236** [comment]
I have repurposed this PR to remove `dist-feed` from `sumo`. Please submit this only after default branch is changed to hardknott.

**Review by amstewart — APPROVED** [review]

**Comment by amstewart** [comment]
> I have repurposed this PR to remove dist-feed from sumo. Please submit this only after default branch is changed to hardknott.

So, now? Did you switch the heisenberg job?

**Comment by chaitu236** [comment]
> So, now? Did you switch the heisenberg job?

Yes, I switched heisenberg job to `nilrt/master/hardknott`. If you switched default branch for NILRT repos to `nilrt/master/hardknott`, this PR can be merged.

**Comment by amstewart** [comment]
Waiting for @billpittman's review.

**Review by billpittman — APPROVED** [review]

**Pull request merged**
