### PR TITLE
Update generated changelogs

### PR DESCRIPTION
**Pull request by mike-petersen-ni**
[AB#2308603](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2308603)

This should be cherry-picked into `nilrt/master/hardknott` and `nilrt/master/kirkstone`.

### CODE REVIEW

**Review by chaitu236 — APPROVED** [review]

**Comment by chaitu236** [comment]
@mike-petersen-ni wouldn't the files be different for kirkstone?

**Comment by chaitu236** [comment]
Cherrypicked into `nilrt/master/hardknott`

**Comment by mike-petersen-ni** [comment]
@chaitu236 
> wouldn't the files be different for kirkstone?

Last time (#228) we had cherry-picked to both. I think the principle is that the changelog tracks all updates, not just those for a certain codename; eventually kirkstone will become the default HEAD and that'll be what users end up looking at.

**Comment by chaitu236** [comment]
Got it, so like our [other CHANGELOG](https://github.com/ni/nilrt/blob/nilrt/master/hardknott/CHANGELOG.md). Cherry picked to `nilrt/master/kirkstone`

**Pull request merged**
